import Head from "next/head";
import { getAllProducts } from "../lib/product";
import ProductList from "../components/product/ProductList"

export default function Home({ allDatas }) {
  const parsedData = JSON.parse(allDatas);
  const products = parsedData.data;
  return (
    <div>
      <Head>
        <title>Phong Vu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProductList products={products}></ProductList>
    </div>
  );
}

export async function getStaticProps() {
  const allDatas = await getAllProducts();
  return { props: { allDatas }, revalidate: 3600 };
}
