import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.sass";
import { getAllProducts } from "../lib/product";
import Layout from "../components/Layout";

export default function Home({ allDatas }) {
  const parsedData = JSON.parse(allDatas);
  const products = parsedData.data;
  return (
    <div>
      <Head>
        <title>Phong Vu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <div className={styles.product}>
          <span className={styles.title__span}>Sản phẩm</span>
          <div className={styles["product-container"]}>
            {products.map((product) => {
              return (
                <Link key={product._id} href={`/product/${product._id}`}>
                  <div className={styles.product__detail}>
                    <img
                      className={styles["product-image__img"]}
                      src={product.image}
                      alt=""
                    />
                    <p className={styles["product-name__p"]}>{product.name}</p>
                    <span className={styles["product-price__span"]}>
                      {product.price}
                    </span>
                  </div>
                </Link>
              );
            })}
          </div>
        </div>
      </Layout>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}

export async function getStaticProps() {
  const allDatas = await getAllProducts();
  return { props: { allDatas } };
}
