import Head from "next/head";
import { getAllProducts } from "../lib/product";
import ProductList from "../components/product/ProductList";
import { useRouter } from "next/router";

export default function Search({ allDatas }) {
  const router = useRouter();
  const parsedData = JSON.parse(allDatas);
  const products = parsedData.data.filter(
    (product) =>
      product.name.toLowerCase().includes(router.query.name) ||
      product.sku.toLowerCase().includes(router.query.name)
  );
  if (products[0]) {
    return (
      <>
        <Head>
          <title>Tìm kiếm</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <ProductList products={products} title="Kết quả tìm kiếm"></ProductList>
      </>
    );
  } else {
    return (
      <>
        <Head>
          <title>Phong Vu</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <p>Không tìm thấy sản phẩm</p>
      </>
    );
  }
}

export async function getStaticProps() {
  const allDatas = await getAllProducts();
  return { props: { allDatas }, revalidate: 3600 };
}
